### ISSUE TITLE
Crash with UndergroundBiomes

### ISSUE THREAD

**Issue by kellixon** [portablejim/BetterBuildersWands#103]
MC 1.12.2. Forge 14.23.5.2825. BetterBuildersWands 0.13.2.271+UndergroundBiomes 1.3.2.
Crash the game when build blocks from UndergroundBiomes.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2019-04-13 18:23:53 MSK
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 14
    at exterminatorjeff.undergroundbiomes.common.block.UBOreMetamorphic.getStateForPlacement(UBOreMetamorphic.java:42)
    at net.minecraft.block.Block.getStateForPlacement(Block.java:2259)
    at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:84)
    at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:53)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1716_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
    at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callBoolean(Reflector.java:680)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1819)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1613)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1384)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [GCEntityClientPlayerMP['kellixon'/84, l='MpServer', x=484.67, y=34.33, z=-481.59]]
  Chunk stats: MultiplayerChunkCache: 272, 272
  Level seed: 0
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (188,64,244), Chunk: (at 12,4,4 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 171172 game time, 57255 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 9 total; [EntityChicken['Курица'/28766, l='MpServer', x=487.20, y=79.00, z=-528.37], EntityChicken['Курица'/28767, l='MpServer', x=493.87, y=79.00, z=-533.50], EntityChicken['Курица'/28768, l='MpServer', x=484.80, y=80.00, z=-529.80], EntityChicken['Курица'/8817, l='MpServer', x=489.13, y=74.00, z=-522.55], GCEntityClientPlayerMP['kellixon'/84, l='MpServer', x=484.67, y=34.33, z=-481.59], EntityWoodpecker['Дятел'/3796, l='MpServer', x=510.51, y=74.49, z=-490.60], EntityPig['Свинья'/1783, l='MpServer', x=412.28, y=71.00, z=-427.50], EntityPig['Свинья'/1913, l='MpServer', x=485.50, y=74.00, z=-495.30], EntityPig['Свинья'/1915, l='MpServer', x=482.17, y=73.00, z=-495.19]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_202, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2704607152 bytes (2579 MB) / 7087849472 bytes (6759 MB) up to 9544663040 bytes (9102 MB)
  JVM Flags: 2 total; -Xmx10G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2825 Optifine OptiFine_1.12.2_HD_U_E3 173 mods loaded, 173 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                      | Version                 | Source                               | Signature                                |
       |:------ |:----------------------- |:----------------------- |:------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft               | 1.12.2                  | minecraft.jar                        | None                                     |
       | LCHIJA | mcp                     | 9.42                    | minecraft.jar                        | None                                     |
       | LCHIJA | FML                     | 8.0.99.99               | forge-1.12.2-14.23.5.2825.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                   | 14.23.5.2825            | forge-1.12.2-14.23.5.2825.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy       | 1.0.0                   | minecraft.jar                        | None                                     |
       | LCHIJA | itemphysic              | 1.4.0                   | minecraft.jar                        | None                                     |
       | LCHIJA | micdoodlecore           |                         | minecraft.jar                        | None                                     |
       | LCHIJA | smoothfontcore          | mc1.12.2-2.0-alpha-7    | minecraft.jar                        | None                                     |
       | LCHIJA | randompatches           | 1.12.2-1.15.0.2         | RandomPatches 1.15.0.2.jar           | None                                     |
       | LCHIJA | techguns_core           | 1.12.2-1.0              | minecraft.jar                        | None                                     |
       | LCHIJA | smoothfont              | mc1.12.2-2.0-alpha-9    | SmoothFont 2.0-a9.jar                | None                                     |
       | LCHIJA | actuallyadditions       | 1.12.2-r146             | ActuallyAdditions r146.jar           | None                                     |
       | LCHIJA | forgelin                | 1.8.2                   | Forgelin 1.8.2.jar                   | None                                     |
       | LCHIJA | alib                    | 1.0.8                   | ALib 1.0.8.jar                       | None                                     |
       | LCHIJA | crafttweaker            | 4.1.17                  | CraftTweaker2 4.1.17.jar             | None                                     |
       | LCHIJA | alchemistry             | 0.9.2                   | Alchemistry 0.9.2.jar                | None                                     |
       | LCHIJA | applecore               | 3.2.0                   | AppleCore 3.2.0.jar                  | None                                     |
       | LCHIJA | jei                     | 4.15.0.275              | JEI 4.15.0.275.jar                   | None                                     |
       | LCHIJA | appleskin               | 1.0.9                   | AppleSkin 1.0.9.jar                  | None                                     |
       | LCHIJA | architecturecraft       | @VERSION@               | ArchitectureCraft 3.80.jar           | None                                     |
       | LCHIJA | baubles                 | 1.5.2                   | Baubles 1.5.2.jar                    | None                                     |
       | LCHIJA | atum                    | 2.0.3                   | Atum 2.0.3.jar                       | None                                     |
       | LCHIJA | B3M                     | 1.12.2-12               | B3M 1.12.2-12.jar                    | None                                     |
       | LCHIJA | betteradvancements      | 0.1.0.77                | BetterAdvancements 0.1.0.77.jar      | None                                     |
       | LCHIJA | betteranimals           | 3.1                     | BetterAnimals 4.0.jar                | None                                     |
       | LCHIJA | betteranimalsplus       | 5.0.2                   | BetterAnimalsPlus 5.0.2.jar          | None                                     |
       | LCHIJA | betterbuilderswands     | 0.13.2                  | BetterBuildersWands 0.13.2.271.jar   | None                                     |
       | LCHIJA | ic2                     | 2.8.120-ex112           | IC2 2.8.120-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | forestry                | 5.8.2.387               | Forestry 5.8.2.387.jar               | None                                     |
       | LCHIJA | binniecore              | 2.5.1.188               | Binnie 2.5.1.188.jar                 | None                                     |
       | LCHIJA | binniedesign            | 2.5.1.188               | Binnie 2.5.1.188.jar                 | None                                     |
       | LCHIJA | genetics                | 2.5.1.188               | Binnie 2.5.1.188.jar                 | None                                     |
       | LCHIJA | botany                  | 2.5.1.188               | Binnie 2.5.1.188.jar                 | None                                     |
       | LCHIJA | extrabees               | 2.5.1.188               | Binnie 2.5.1.188.jar                 | None                                     |
       | LCHIJA | extratrees              | 2.5.1.188               | Binnie 2.5.1.188.jar                 | None                                     |
       | LCHIJA | biomesoplenty           | 7.0.1.2426              | BiomesOPlenty 7.0.1.2426.jar         | None                                     |
       | LCHIJA | birdsfoods              | 3.1 - [1.12]            | BirdsFoods 3.1.jar                   | None                                     |
       | LCHIJA | thaumcraft              | 6.1.BETA26              | Thaumcraft 6.1.b26.jar               | None                                     |
       | LCHIJA | botania                 | r1.10-361               | Botania r1.10-361.jar                | None                                     |
       | LCHIJA | bountiful               | 2.2.0                   | Bountiful 2.2.0.jar                  | None                                     |
       | LCHIJA | codechickenlib          | 3.2.2.354               | CodeChickenLib 3.2.2.354.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux            | 2.1.0                   | RedstoneFlux 2.1.0.6.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | brandonscore            | 2.4.10                  | BrandonsCore 2.4.10.198.jar          | None                                     |
       | LCHIJA | carryon                 | 1.12.1                  | CarryOn 1.12.1.jar                   | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHIJA | cavern                  | 2.1.9                   | Cavern 2.1.9.jar                     | b78e30ad27c82f3e348f76edf497058678207299 |
       | LCHIJA | chameleon               | 1.12-4.1.3              | Chameleon 4.1.3.jar                  | None                                     |
       | LCHIJA | ctm                     | MC1.12.2-0.3.3.22       | CTM 0.3.3.22.jar                     | None                                     |
       | LCHIJA | chisel                  | MC1.12.2-0.2.1.35       | Chisel 0.2.1.35.jar                  | None                                     |
       | LCHIJA | chunkpregenerator       | 2.1                     | ChunkPregenerator 2.1.jar            | None                                     |
       | LCHIJA | cofhcore                | 4.6.2                   | CoFHCore 4.6.2.25.jar                | None                                     |
       | LCHIJA | cofhworld               | 1.3.0                   | CoFHWorld 1.3.0.6.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | comforts                | 1.4.1.1                 | Comforts 1.4.1.1.jar                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | compactstorage          | 3.1                     | CompactStorage 3.1-12.jar            | None                                     |
       | LCHIJA | controlling             | 3.0.6                   | Controlling 3.0.6.jar                | None                                     |
       | LCHIJA | cookingforblockheads    | 6.4.70                  | CookingForBlockheads 6.4.70.jar      | None                                     |
       | LCHIJA | ctgui                   | 1.0.0                   | CraftTweaker2 4.1.17.jar             | None                                     |
       | LCHIJA | crafttweakerjei         | 2.0.3                   | CraftTweaker2 4.1.17.jar             | None                                     |
       | LCHIJA | creativecore            | 1.9.9                   | CreativeCore 1.9.42.jar              | None                                     |
       | LCHIJA | cucumber                | 1.1.3                   | CucumberLib 1.1.3.jar                | None                                     |
       | LCHIJA | cyclicmagic             | 1.19.2                  | Cyclic 1.19.2.jar                    | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LCHIJA | cyclopscore             | 1.1.1                   | CyclopsCore 1.1.1.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | eleccore                | 1.9.452                 | ElecCore 1.9.452.jar                 | None                                     |
       | LCHIJA | mcjtylib_ng             | 3.1.1                   | McJtyLib 3.1.1.jar                   | None                                     |
       | LCHIJA | rftools                 | 7.61                    | RFTools 7.61.jar                     | None                                     |
       | LCHIJA | deepresonance           | 1.7.6                   | DeepResonance 1.7.6.jar              | None                                     |
       | LCHIJA | defaultlanport          | 1.0                     | DefaultLANPort 1.0.jar               | None                                     |
       | LCHIJA | thermalfoundation       | 2.6.2                   | ThermalFoundation 2.6.2.26.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | draconicevolution       | 2.3.21                  | DraconicEvolution 2.3.21.342.jar     | None                                     |
       | LCHIJA | elevatorid              | 1.3.8                   | ElevatorMod 1.3.8.jar                | None                                     |
       | LCHIJA | embers                  | 1.13-hotfix2            | EmbersRekindled 1.13-hf2.jar         | None                                     |
       | LCHIJA | enchcontrol             | 1.1.4                   | EnchControl 1.1.4-0.jar              | 22cc4f45e4341b5bf2de5964a37e0165d157c9a2 |
       | LCHIJA | enderstorage            | 2.4.5.136               | EnderStorage 2.4.5.136.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | reborncore              | 3.13.12.447             | RebornCore 3.13.12.447.jar           | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | engineersworkshop       | 1.0.9.40                | EngineersWorkshopReborn 1.0.9.40.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | enhancedvisuals         | 1.0                     | EnhancedVisuals 1.2.1.jar            | None                                     |
       | LCHIJA | evilcraft               | 0.10.72                 | EvilCraft 0.10.72.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | evilcraftcompat         | 1.0.0                   | EvilCraft 0.10.72.jar                | None                                     |
       | LCHIJA | exoticbirds             | 1.0                     | ExoticBirds 2.2.1.jar                | None                                     |
       | LCHIJA | galacticraftcore        | 4.0.2.210               | GalacticraftCore 4.0.2.210.jar       | None                                     |
       | LCHIJA | galacticraftplanets     | 4.0.2.210               | GalacticraftPlanets 4.0.2.210.jar    | None                                     |
       | LCHIJA | mjrlegendslib           | 1.12.2-1.1.8            | MJRLegendsLib 1.1.8.jar              | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | extraplanets            | 1.12.2-0.5.2            | ExtraPlanets 0.5.2.jar               | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | farmingforblockheads    | 3.1.26                  | FarmingForBlockheads 3.1.26.jar      | None                                     |
       | LCHIJA | sonarcore               | 5.0.19                  | SonarCore 5.0.19-20.jar              | None                                     |
       | LCHIJA | fluxnetworks            | 3.0.19                  | FluxNetworks 3.0.19-21.jar           | None                                     |
       | LCHIJA | ftblib                  | 5.4.1.95                | FTBLib 5.4.1.95.jar                  | None                                     |
       | LCHIJA | ftbutilities            | 5.4.0.92                | FTBUtilities 5.4.0.92.jar            | None                                     |
       | LCHIJA | ftbbackups              | 0.0.0.ftbbackups        | FTBUtilitiesBackups 1.0.0.3.jar      | None                                     |
       | LCHIJA | helpfixer               | 1.12.1-1.5.18           | HelpFixer 1.5.18.jar                 | None                                     |
       | LCHIJA | increasemobs            | 1.1.0                   | IncreaseMobs 1.1.0.jar               | None                                     |
       | LCHIJA | teslacorelib            | 1.0.15                  | TeslaCoreLib 1.0.15.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | industrialforegoing     | 1.12.2-1.12.2           | IndustrialForegoing 1.12.11-235.jar  | None                                     |
       | LCHIJA | lunatriuscore           | 1.2.0.42                | LunatriusCore 1.2.0.42.jar           | None                                     |
       | LCHIJA | ingameinfoxml           | 2.8.2.94                | InGameInfoXML 2.8.2.94.jar           | None                                     |
       | LCHIJA | igi|thaumcraft          | 1.0a                    | InGameInfoXMLThaumcraft 1.0a.jar     | None                                     |
       | LCHIJA | mysticalagriculture     | 1.7.3                   | MysticalAgriculture 1.7.3.jar        | None                                     |
       | LCHIJA | integrationforegoing    | 1.12.2-1.9              | IntegrationForegoing 1.9.jar         | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHIJA | inventorytweaks         | 1.64+dev.146.2180b27    | InventoryTweaks 1.64.jar             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | jeibees                 | 0.9.0.5                 | JEIBees 0.9.0.5.jar                  | None                                     |
       | LCHIJA | jeresources             | 0.9.0.53                | JEIResources 0.9.0.53.jar            | None                                     |
       | LCHIJA | thaumicjei              | 1.5.8                   | JEIThaumic 1.5.8-26.jar              | None                                     |
       | LCHIJA | laggoggles              | FORGE-1.12.2-4.1        | LagGoggles 4.1.jar                   | None                                     |
       | LCHIJA | fluidtank               | 4.1                     | LargeFluidTank 4.1.jar               | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
       | LCHIJA | fluidtank_ae2           | 4.1                     | LargeFluidTank 4.1.jar               | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
       | LCHIJA | fluidtank_theoneprobe   | 4.1                     | LargeFluidTank 4.1.jar               | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
       | LCHIJA | leafdecay               | 1.0.0.2                 | LeafDecayAccelerator 1.0.0.2.jar     | None                                     |
       | LCHIJA | logfilters              | 1.0.0                   | LogFilters 1.0.0.jar                 | None                                     |
       | LCHIJA | lootablebodies          | 2.4.0                   | LootableBodies 2.4.0.jar             | None                                     |
       | LCHIJA | manavisualizer          | r1.0-1                  | ManaVisualizer 1.0-1.jar             | None                                     |
       | LCHIJA | mpr                     | 2.3.0                   | MobsPropertiesRandomness 2.3.0.jar   | None                                     |
       | LCHIJA | modernlamps             | 1.0.3                   | ModernLights 1.0.3.jar               | None                                     |
       | LCHIJA | modnametooltip          | 1.10.0                  | ModNameTooltip 1.10.0.jar            | None                                     |
       | LCHIJA | moreoverlays            | 1.14                    | MoreOverlays 1.14.jar                | None                                     |
       | LCHIJA | morerecipes             | 3.3                     | MoreRecipes 3.3.jar                  | None                                     |
       | LCHIJA | mousetweaks             | 2.10                    | MouseTweaks 2.10.jar                 | None                                     |
       | LCHIJA | cfm                     | 6.2.0                   | MrCrayfish'sFurniture 6.2.0.jar      | None                                     |
       | LCHIJA | naturescompass          | 1.5.1                   | NaturesCompass 1.5.1.jar             | None                                     |
       | LCHIJA | neat                    | 1.4-17                  | Neat 1.4-17.jar                      | None                                     |
       | LCHIJA | netherportalfix         | 5.3.17                  | NetherPortalFix 5.3.17.jar           | None                                     |
       | LCHIJA | nomobbat                | 1.1                     | NoBat 1.0.jar                        | None                                     |
       | LCHIJA | recipehandler           | 0.12                    | NoMoreRecipeConflict 0.12.jar        | None                                     |
       | LCHIJA | nopoles                 | @VERSION@               | NoPoles 3.1.6.jar                    | None                                     |
       | LCHIJA | norecipebook            | 1.2.1                   | NoRecipeBook 1.2.2.jar               | None                                     |
       | LCHIJA | neid                    | 1.5.4.4                 | NotEnoughIDs 1.5.4.4.jar             | None                                     |
       | LCHIJA | notenoughwands          | 1.7.3                   | NotEnoughWands 1.7.3.jar             | None                                     |
       | LCHIJA | pa                      | 1.12.2                  | PassiveAggression 0.0.1.jar          | None                                     |
       | LCHIJA | patchouli               | 1.0-18                  | Patchouli 1.0-18.jar                 | None                                     |
       | LCHIJA | pickletweaks            | 2.1.2                   | PickleTweaks 2.1.2.jar               | None                                     |
       | LCHIJA | prefab                  | 1.3.0.26                | Prefab 1.3.0.26.jar                  | None                                     |
       | LCHIJA | railcraft               | 12.0.0                  | Railcraft 12.0.0.jar                 | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | randomthings            | 4.2.7.1                 | RandomThings 4.2.7.1.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | thermalexpansion        | 5.5.3                   | ThermalExpansion 5.5.3.41.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | redstonearsenal         | 2.6.2                   | RedstoneArsenal 2.6.2.17.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | redstonepaste           | 1.7.5                   | RedstonePaste 1.7.5.jar              | None                                     |
       | LCHIJA | refinedstorage          | 1.6.14                  | RefinedStorage 1.6.14.jar            | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | refinedstorageaddons    | 0.4.4                   | RefinedStorageAddons 0.4.4.jar       | None                                     |
       | LCHIJA | rad                     | 1.0.2                   | ReloadAudioDriver 1.0.2.jar          | None                                     |
       | LCHIJA | reptilemod              | 3.8.4                   | Reptile 3.8.4-89.jar                 | None                                     |
       | LCHIJA | rftoolspower            | 1.1.2                   | RFToolsPower 1.1.2.jar               | None                                     |
       | LCHIJA | roguelike               | 1.8.0                   | RoguelikeDungeons 1.8.0.jar          | None                                     |
       | LCHIJA | roost                   | 1.3.0                   | Roost 1.3.0.jar                      | None                                     |
       | LCHIJA | roots                   | 0.104                   | Roots 2-0.104.jar                    | None                                     |
       | LCHIJA | ruins                   | 17.1                    | Ruins 17.2.jar                       | None                                     |
       | LCHIJA | schematica              | 1.8.0.169               | Schematica 1.8.0.169.jar             | None                                     |
       | LCHIJA | servertabinfo           | 1.2.4                   | ServerTabInfo 1.2.4.jar              | None                                     |
       | LCHIJA | slideemall              | 0.94.1                  | SlideemAll 0.94.1.jar                | None                                     |
       | LCHIJA | soundfilters            | 0.10_for_1.12           | SoundFilters 0.10.jar                | None                                     |
       | LCHIJA | terracore               | 2.1.13                  | TerraCore 1.13.jar                   | None                                     |
       | LCHIJA | stats_keeper            | 3.1.12                  | StatsKeeper 3.1.12.jar               | None                                     |
       | LCHIJA | storagedrawers          | 1.12-5.3.5              | StorageDrawers 5.3.8.jar             | None                                     |
       | LCHIJA | techguns                | 2.0.1.2                 | TechGuns 2.0.1.2-1.jar               | None                                     |
       | LCHIJA | thaumcraftnoresearch    | 1.0                     | ThaumcraftNoResearch 1.0.jar         | None                                     |
       | LCHIJA | tcinventoryscan         | 2.0.10                  | ThaumicInventoryScanning 2.0.10.jar  | None                                     |
       | LCHIJA | theoneprobe             | 1.4.28                  | TheOneProbe 1.4.28.jar               | None                                     |
       | LCHIJA | thermaldynamics         | 2.5.4                   | ThermalDynamics 2.5.4.18.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalinnovation       | 0.3.2                   | ThermalInnovation 0.3.2.11.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | topaddons               | 1.12.2-1.10.1           | TOPAddons 1.10.1.jar                 | None                                     |
       | LCHIJA | torchmaster             | 1.7.1.74                | TorchMaster 1.7.1.74.jar             | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHIJA | undergroundbiomes       | 1.3.2                   | UndergroundBiomes 1.3.2.jar          | None                                     |
       | LCHIJA | vanillafix              | 1.0.10-SNAPSHOT         | VanillaFix 1.0.10-99.jar             | None                                     |
       | LCHIJA | veinminer               | 0.38.1                  | VeinMiner 0.38.1.639.jar             | None                                     |
       | LCHIJA | veinminermodsupport     | 0.38.1                  | VeinMiner 0.38.1.639.jar             | None                                     |
       | LCHIJA | wanionlib               | 1.12.2-2.2              | WanionLib 2.2.jar                    | None                                     |
       | LCHIJA | wts                     | 1.1.0                   | What'sThatSlot 1.1.0.jar             | None                                     |
       | LCHIJA | wirelessutils           | 1.6                     | WirelessUtils 1.6.51.jar             | None                                     |
       | LCHIJA | worldedit               | 6.1.10-SNAPSHOT         | WorldEdit 6.1.10.jar                 | None                                     |
       | LCHIJA | xaerominimap            | 1.16.3                  | XaerosMiniMap 1.16.3.jar             | None                                     |
       | LCHIJA | xaeroworldmap           | 1.3.4.1                 | XaerosWorldMap 1.3.4.1.jar           | None                                     |
       | LCHIJA | yabba                   | 1.1.2.48                | YABBA 1.1.2.48.jar                   | None                                     |
       | LCHIJA | eleccoreloader          | 1.9.452                 | ElecCore 1.9.452.jar                 | None                                     |
       | LCHIJA | hungeroverhaul          | 1.12.2-1.3.3.jenkins148 | HungerOverhaul 1.3.3-148.jar         | None                                     |
       | LCHIJA | teslacorelib_registries | 1.0.15                  | TeslaCoreLib 1.0.15.jar              | None                                     |
       | LCHIJA | unidict                 | 1.12.2-2.9.2            | UniDict 2.9.2.jar                    | None                                     |
  Loaded coremods (and transformers): Techguns Core (TechGuns 2.0.1.2-1.jar)
                                        techguns.core.TechgunsASMTransformer
                                      CorePlugin (SmoothFont 2.0-a9.jar)
                                        bre.smoothfont.asm.Transformer
                                      AppleCore (AppleCore 3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      Inventory Tweaks Coremod (InventoryTweaks 1.64.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Enchantments Control Core (EnchControl 1.1.4-0.jar)
                                        austeretony.enchcontrol.common.core.ECClassTransformer
                                      CreativePatchingLoader (CreativeCore 1.9.42.jar)
                                        
                                      ItemPatchingLoader (ItemPhysicFull 1.4.19.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      NWRTweak (RedstonePaste 1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      Alchemistry Plugin (Alchemistry 0.9.2.jar)
                                        al132.alchemistry.core.AlchemistryTransformer
                                      Default LAN Port (DefaultLANPort 1.0.jar)
                                        core.defaultlanport.coretransform.CoreTransformer
                                      MicdoodlePlugin (MicdoodleCore 4.0.2.210.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      VanillaFixLoadingPlugin (VanillaFix 1.0.10-99.jar)
                                        
                                      ForgelinPlugin (Forgelin 1.8.2.jar)
                                        
                                      Plugin (NotEnoughIDs 1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      RandomPatches (RandomPatches 1.15.0.2.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      B3M_CorePlugin (B3M 1.12.2-12.jar)
                                        sedridor.B3M.core.B3M_Transformer
                                      LoadingPlugin (RandomThings 4.2.7.1.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      LogFilters (LogFilters 1.0.0.jar)
                                        
                                      RBLoadingPlugin (RealBench 1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      CTMCorePlugin (CTM 0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.67' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.13.12.447
              Runtime Debofucsation 1
              RenderEngine: 1
  forestry : Modules have been disabled in the config: Extra Utilities, ImmersiveEngineering, Crate, BuildCraft 6 Transport, rustic, HarvestCraft, EnderIO, IndustrialCraft2, BuildCraft 6 Recipes, BuildCraft 6 Statements, Better With Mods, TechReborn, Lepidopterology, Natura, BuildCraft 6 Fuels, Database
  Suspected Mods: Underground Biomes (undergroundbiomes), Better Builder's Wands (betterbuilderswands)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2825
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.67, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 5.[32x]FaithfulMods 12.04.zip, 4.[32x]Faithful 5.0.zip, 3.[1.12.2]RuLang by kellixon 1.0.zip, 2.[1.12.2]Sn0wSongSound 2.05.zip, 1.[1.12.2]Sn0wSongMusic 1.0.zip, NoLevelUp.zip
  Current Language: Русский (Россия)
  Profiler Position: N/A (disabled)
  CPU: 8x AMD FX-8320E Eight-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by DrewTamashi** [comment]
specifically i was getting this issue whenever looking at any of the ores. the wand for me worked fine for stone/ cobble
