### ISSUE TITLE
Crash occurred when hitting Redstone Ore with "Unbreakable Builder's Wand"

### ISSUE THREAD

**Issue by DuelMonster** [portablejim/BetterBuildersWands#14]
This same crash occurs every time I load my world now...

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 12/14/16 1:25 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemStack.func_77981_g(ItemStack.java:234)
	at portablejim.bbw.shims.BasicPlayerShim.getBlockMeta(BasicPlayerShim.java:33)
	at portablejim.bbw.shims.BasicPlayerShim.countItems(BasicPlayerShim.java:53)
	at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:49)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callBoolean(Reflector.java:352)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77981_g(ItemStack.java:234)
	at portablejim.bbw.shims.BasicPlayerShim.getBlockMeta(BasicPlayerShim.java:33)
	at portablejim.bbw.shims.BasicPlayerShim.countItems(BasicPlayerShim.java:53)
	at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:49)
	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:52)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callBoolean(Reflector.java:352)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DuelMonster'/949, l='MpServer', x=-124.34, y=10.00, z=221.82]]
	Chunk stats: MultiplayerChunkCache: 841, 841
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-108,64,256), Chunk: (at 4,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 66491319 game time, 7856153 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 92 total; [EntitySkeleton['Skeleton'/10497, l='MpServer', x=-191.50, y=53.00, z=253.50], EntityBat['Bat'/3074, l='MpServer', x=-118.51, y=24.98, z=218.22], EntityCreeper['Creeper'/12038, l='MpServer', x=-168.50, y=37.00, z=292.50], EntityPig['Pig'/266, l='MpServer', x=-91.70, y=68.00, z=146.50], EntitySquid['Squid'/11531, l='MpServer', x=-59.35, y=62.01, z=213.31], EntitySquid['Squid'/11532, l='MpServer', x=-60.45, y=60.01, z=224.01], EntitySkeleton['Skeleton'/12054, l='MpServer', x=-175.50, y=19.00, z=250.50], EntitySpider['Spider'/12055, l='MpServer', x=-176.50, y=19.00, z=248.54], EntityEnderman['Enderman'/11800, l='MpServer', x=-148.50, y=20.00, z=252.50], EntitySpider['Spider'/12056, l='MpServer', x=-174.95, y=19.00, z=245.91], EntitySpider['Spider'/12057, l='MpServer', x=-178.05, y=19.00, z=245.91], EntityPig['Pig'/282, l='MpServer', x=-90.22, y=68.00, z=148.49], EntityPig['Pig'/283, l='MpServer', x=-89.93, y=68.00, z=145.61], EntitySpider['Spider'/11548, l='MpServer', x=-198.32, y=13.02, z=294.73], EntityCow['Cow'/286, l='MpServer', x=-85.55, y=62.38, z=202.44], EntityBat['Bat'/10785, l='MpServer', x=-171.12, y=19.23, z=253.14], EntityCow['Cow'/298, l='MpServer', x=-69.36, y=62.47, z=221.34], EntityCow['Cow'/299, l='MpServer', x=-60.30, y=66.00, z=295.36], EntityPig['Pig'/309, l='MpServer', x=-42.72, y=63.00, z=220.40], EntityBat['Bat'/11834, l='MpServer', x=-172.25, y=34.20, z=241.20], EntityCreeper['Creeper'/11599, l='MpServer', x=-135.50, y=51.00, z=192.50], EntityCreeper['Creeper'/9554, l='MpServer', x=-174.50, y=40.00, z=237.50], EntityBat['Bat'/2901, l='MpServer', x=-122.77, y=27.29, z=212.79], EntityBat['Bat'/9048, l='MpServer', x=-82.25, y=36.10, z=190.54], EntityBat['Bat'/11866, l='MpServer', x=-139.29, y=27.24, z=197.35], EntityBat['Bat'/1893, l='MpServer', x=-124.55, y=26.76, z=214.47], EntitySkeleton['Skeleton'/9317, l='MpServer', x=-167.50, y=19.00, z=252.50], EntityZombie['Zombie'/11884, l='MpServer', x=-165.50, y=37.00, z=263.50], EntityZombie['Zombie'/11886, l='MpServer', x=-165.50, y=37.00, z=264.50], EntityZombie['Zombie'/11888, l='MpServer', x=-163.50, y=37.00, z=265.50], EntityZombie['Zombie'/10612, l='MpServer', x=-126.50, y=51.00, z=203.50], EntityCreeper['Creeper'/11384, l='MpServer', x=-167.50, y=62.00, z=258.50], EntityBat['Bat'/10634, l='MpServer', x=-72.02, y=15.53, z=160.86], EntitySpider['Spider'/10133, l='MpServer', x=-144.50, y=51.00, z=194.50], EntityCreeper['Creeper'/11925, l='MpServer', x=-197.48, y=46.17, z=296.71], EntitySkeleton['Skeleton'/11670, l='MpServer', x=-156.50, y=27.00, z=263.50], EntityZombie['Zombie'/11926, l='MpServer', x=-191.50, y=44.00, z=293.50], EntityCreeper['Creeper'/11163, l='MpServer', x=-143.50, y=44.00, z=278.50], EntityCreeper['Creeper'/11680, l='MpServer', x=-130.50, y=48.00, z=279.50], EntityCreeper['Creeper'/11681, l='MpServer', x=-123.50, y=48.00, z=278.50], EntityZombie['Zombie'/11682, l='MpServer', x=-154.50, y=33.00, z=230.50], EntityZombie['Zombie'/10919, l='MpServer', x=-200.71, y=63.00, z=274.51], EntitySkeleton['Skeleton'/11432, l='MpServer', x=-118.50, y=51.00, z=275.50], EntityPig['Pig'/170, l='MpServer', x=-197.33, y=66.00, z=186.45], EntityPig['Pig'/171, l='MpServer', x=-192.26, y=66.00, z=180.53], EntityPig['Pig'/172, l='MpServer', x=-198.49, y=66.00, z=211.30], EntitySkeleton['Skeleton'/11948, l='MpServer', x=-124.50, y=39.00, z=254.50], EntityPig['Pig'/173, l='MpServer', x=-194.87, y=70.00, z=254.55], EntityZombie['Zombie'/10925, l='MpServer', x=-152.47, y=32.00, z=234.21], EntitySkeleton['Skeleton'/10926, l='MpServer', x=-149.50, y=30.00, z=228.50], EntityVillager['Villager'/175, l='MpServer', x=-198.81, y=73.00, z=272.11], EntityVillager['Villager'/176, l='MpServer', x=-199.63, y=73.00, z=270.70], EntityVillager['Villager'/179, l='MpServer', x=-196.50, y=72.00, z=277.70], EntitySkeleton['Skeleton'/8631, l='MpServer', x=-104.50, y=35.00, z=237.50], EntitySpider['Spider'/4536, l='MpServer', x=-135.17, y=31.10, z=207.30], EntityPig['Pig'/185, l='MpServer', x=-195.22, y=66.00, z=180.49], EntityPig['Pig'/186, l='MpServer', x=-177.49, y=64.00, z=177.77], EntityPlayerSP['DuelMonster'/949, l='MpServer', x=-124.34, y=10.00, z=221.82], EntityPig['Pig'/187, l='MpServer', x=-178.51, y=64.00, z=191.23], EntityZombie['Zombie'/9660, l='MpServer', x=-130.50, y=20.00, z=255.50], EntityPig['Pig'/189, l='MpServer', x=-191.60, y=65.00, z=207.60], EntityPig['Pig'/190, l='MpServer', x=-184.80, y=64.00, z=195.81], EntityPig['Pig'/203, l='MpServer', x=-181.27, y=88.00, z=140.50], EntityPig['Pig'/204, l='MpServer', x=-171.50, y=82.00, z=144.22], EntitySkeleton['Skeleton'/11980, l='MpServer', x=-155.08, y=16.00, z=270.24], EntityPig['Pig'/205, l='MpServer', x=-172.48, y=82.00, z=145.16], EntitySkeleton['Skeleton'/11981, l='MpServer', x=-151.50, y=16.00, z=266.50], EntityPig['Pig'/206, l='MpServer', x=-167.78, y=65.00, z=194.70], EntitySkeleton['Skeleton'/11982, l='MpServer', x=-154.03, y=16.00, z=271.70], EntityPig['Pig'/207, l='MpServer', x=-171.30, y=66.00, z=218.50], EntitySkeleton['Skeleton'/11983, l='MpServer', x=-154.59, y=16.00, z=271.08], EntityPig['Pig'/209, l='MpServer', x=-172.70, y=67.00, z=238.49], EntityZombie['Zombie'/11730, l='MpServer', x=-176.50, y=17.00, z=174.50], EntitySkeleton['Skeleton'/10715, l='MpServer', x=-104.50, y=19.00, z=241.50], EntitySkeleton['Skeleton'/10981, l='MpServer', x=-193.50, y=44.00, z=256.50], EntityPig['Pig'/233, l='MpServer', x=-137.15, y=65.00, z=154.87], EntityBat['Bat'/12011, l='MpServer', x=-147.45, y=21.69, z=255.42], EntityCow['Cow'/236, l='MpServer', x=-140.16, y=64.00, z=170.19], EntityBat['Bat'/12012, l='MpServer', x=-147.26, y=20.75, z=252.28], EntityCow['Cow'/237, l='MpServer', x=-142.14, y=64.00, z=171.26], EntityCow['Cow'/238, l='MpServer', x=-140.21, y=65.00, z=183.47], EntitySheep['Sheep'/241, l='MpServer', x=-135.40, y=66.00, z=245.25], EntitySkeleton['Skeleton'/4339, l='MpServer', x=-110.37, y=19.00, z=232.72], EntityBat['Bat'/12019, l='MpServer', x=-201.75, y=54.82, z=242.75], EntityPig['Pig'/244, l='MpServer', x=-120.88, y=67.00, z=141.98], EntityBat['Bat'/3061, l='MpServer', x=-117.56, y=29.52, z=218.24], EntityPig['Pig'/245, l='MpServer', x=-127.32, y=66.00, z=142.84], EntityBat['Bat'/12022, l='MpServer', x=-198.47, y=56.06, z=243.75], EntityPig['Pig'/248, l='MpServer', x=-120.12, y=67.00, z=146.21], EntityCow['Cow'/250, l='MpServer', x=-117.45, y=70.00, z=174.19], EntityCow['Cow'/251, l='MpServer', x=-126.72, y=65.00, z=166.45], EntityCow['Cow'/255, l='MpServer', x=-115.15, y=68.00, z=220.25]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2048765968 bytes (1953 MB) / 3217555456 bytes (3068 MB) up to 5728894976 bytes (5463 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6146m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.2.163} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.163-universal.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.0} [Better Builder's Wands] (BetterBuildersWands-0.8.0-1.10.2r170+8ee7f54.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.145} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.1.5.42} [ChickenChunks] (ChickenChunks-1.10.2-2.1.5.42-universal.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJAAAA	clienttweaks{1.1.16} [Client Tweaks] (ClientTweaks_1.10.2-1.1.16.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UCHIJAAAA	JEI{3.13.6.390} [Just Enough Items] (jei_1.10.2-3.13.6.390.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.138_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.138_beta.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.2.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJAAAA	InGameInfoXML{2.8.1.89} [InGame Info XML] (InGameInfoXML-1.10.2-2.8.1.89-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	jacb{1.0.6} [JACB] (JACB-1.10.2-1.0.6.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCHIJAAAA	jeresources{0.5.7.96} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.96.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	limelib{1.3.5} [LimeLib] (limelib-1.10.2-1.3.5.jar) 
	UCHIJAAAA	malisiscore{1.10.2-4.2.9} [MalisisCore] (malisiscore-1.10.2-4.2.9.jar) 
	UCHIJAAAA	malisisblocks{1.10.2-4.1.3} [Malisis Blocks] (malisisblocks-1.10.2-4.1.3.jar) 
	UCHIJAAAA	malisisdoors{1.10.2-5.1.6} [MalisisDoors] (malisisdoors-1.10.2-5.1.6.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	menumobs{1.14} [Menu Mobs] (MenuMobs-1.10.2-1.14.jar) 
	UCHIJAAAA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	placementpreview{0.3.0} [Placement Preview] (placementpreview-1.10.2-0.3.0.jar) 
	UCHIJAAAA	quantumflux{2.0.9} [QuantumFlux] (quantumflux-1.10.2-2.0.9.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.11} [Storage Drawers] (StorageDrawers-1.10.2-3.5.11.jar) 
	UCHIJAAAA	refinedstorage{1.2.11} [Refined Storage] (refinedstorage-1.2.11.jar) 
	UCHIJAAAA	storagenetwork{1.12.10} [Storage Network] (StorageNetwork-1.10.2-1.12.10-final.jar) 
	UCHIJAAAA	superminer_core{[1.10.2]-2.1.6.105} [SuperMiner] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_captivator{[1.10.2]-2.1.6.105} [SuperMiner Captivator] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_cropinator{[1.10.2]-2.1.6.105} [SuperMiner Copinator] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_excavator{[1.10.2]-2.1.6.105} [SuperMiner Excavator] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_illuminator{[1.10.2]-2.1.6.105} [SuperMiner Illuminator] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_lumbinator{[1.10.2]-2.1.6.105} [SuperMiner Lumbinator] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_shaftanator{[1.10.2]-2.1.6.105} [SuperMiner Shaftanator] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_substitutor{[1.10.2]-2.1.6.105} [SuperMiner Substitutor] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	superminer_veinator{[1.10.2]-2.1.6.105} [SuperMiner Veinator] (SuperMiner-[1.10.2]-2.1.6.105.jar) 
	UCHIJAAAA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (teleporters-1.1.3.jar) 
	UCHIJAAAA	torchmaster{1.0} [TorchMaster] (torchmaster-1.0.1.jar) 
	UCHIJAAAA	visiblearmorslots{2.0} [Visible Armor Slots] (VisibleArmorSlots[1.10.2]-2.0.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
MalisisCorePlugin (malisiscore-1.10.2-4.2.9.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  codechicken.nei.asm.NEITransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4534' Renderer: 'Intel(R) HD Graphics 530'
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/$MC/~Launchers/Andy/Curse/Instances/Testing%201.10.2/mods/extrautils2-1.10.2-1.1.2.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: forge-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4534, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Default Improved.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4534
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 8
```

**Comment by DuelMonster** [comment]
Latest update solved this issue.  Thanks
