### ISSUE TITLE
[1.10.2] Crash with wand

### ISSUE THREAD

**Issue by MrAmericanMike** [portablejim/BetterBuildersWands#22]
This crash happened when I was looking at either a bed or a torch, not sure.

`
[28/12/2016 20:27:21 PM] [20:27:21] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.DrawBlockHighlightEvent@7fef082f:
[28/12/2016 20:27:21 PM] java.lang.NullPointerException
[28/12/2016 20:27:21 PM] 	at net.minecraft.item.ItemStack.func_77981_g(ItemStack.java:234) ~[adz.class:?]
[28/12/2016 20:27:21 PM] 	at portablejim.bbw.shims.BasicPlayerShim.getBlockMeta(BasicPlayerShim.java:33) ~[BasicPlayerShim.class:?]
[28/12/2016 20:27:21 PM] 	at portablejim.bbw.shims.BasicPlayerShim.countItems(BasicPlayerShim.java:53) ~[BasicPlayerShim.class:?]
[28/12/2016 20:27:21 PM] 	at portablejim.bbw.core.WandWorker.getProperItemStack(WandWorker.java:49) ~[WandWorker.class:?]
[28/12/2016 20:27:21 PM] 	at portablejim.bbw.core.BlockEvents.blockHighlightEvent(BlockEvents.java:52) ~[BlockEvents.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_682_BlockEvents_blockHighlightEvent_DrawBlockHighlightEvent.invoke(.dynamic) ~[?:?]
[28/12/2016 20:27:21 PM] 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161) [ForgeHooksClient.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1329) [bnz.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229) [bnz.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038) [bnz.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
[28/12/2016 20:27:21 PM] 	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
[28/12/2016 20:27:21 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
[28/12/2016 20:27:21 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[28/12/2016 20:27:21 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
[28/12/2016 20:27:21 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
[28/12/2016 20:27:21 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[28/12/2016 20:27:21 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: Index: 11 Listeners:
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 0: NORMAL
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 1: ASM: ipsis.buildersguides.client.DrawBlockHighlightEventHandler@50b35189 onDrawBlockHighlightEvent(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 2: ASM: team.chisel.common.item.ItemOffsetTool@32dc5605 onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 3: ASM: codechicken.lib.render.CCRenderEventHandler@68e779cf onBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 4: ASM: fi.dy.masa.enderutilities.event.RenderEventHandler@2430b10d onBlockHilight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 5: ASM: com.rwtema.extrautils2.items.ItemDestructionWand@1ac177ad drawSelection(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 6: ASM: com.rwtema.extrautils2.items.ItemBuildersWand@6fa1add0 drawSelection(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 7: ASM: com.rwtema.extrautils2.items.ItemDestructionWand@6c08096e drawSelection(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 8: ASM: com.rwtema.extrautils2.items.ItemBuildersWand@7f43ada drawSelection(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 9: ASM: moze_intel.projecte.events.TransmutationRenderingEvent@228df27 onOverlay(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 10: ASM: thut.tech.common.items.ItemLinker@193f396a RenderBounds(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 11: ASM: portablejim.bbw.core.BlockEvents@4cc48549 blockHighlightEvent(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 12: ASM: blusunrize.immersiveengineering.client.ClientEventHandler@2898e79a renderAdditionalBlockBounds(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 13: ASM: INSTANCE onDrawBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 14: ASM: mcjty.rftools.proxy.ClientProxy@70e436ee onRenderBlockOutline(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 15: ASM: com.tomevoll.routerreborn.Event.Event@41d5a DrawHighligth(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 16: LOW
[28/12/2016 20:27:21 PM] [Client thread/ERROR] [FML]: 17: ASM: Block{null} onDrawBlockHighlight(Lnet/minecraftforge/client/event/DrawBlockHighlightEvent;)V
[28/12/2016 20:27:27 PM] [Server thread/INFO] [Mekanism]: VoiceServer: Shutting down server...
`

Using BetterBuildersWands-0.8.0-1.10.2r1708ee7f54

**Comment by MrAmericanMike** [comment]
PS: Apparently 0.9.3 fixes it, but gonna leave it open to have confirmation ;)

**Comment by portablejim** [comment]
Yep.
